language: php

sudo: false

git:
    depth: 1

cache:
    directories:
        - $HOME/.composer

env:
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-progress"
        - COMPOSER_FLAGS=""

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

    # Composer: boost installation
    - composer global show hirak/prestissimo -q || travis_retry composer global require $DEFAULT_COMPOSER_FLAGS hirak/prestissimo

jobs:
    include:
        -
            stage: Static Code Analysis
            php: 7.2
            install:
                - travis_retry composer update $DEFAULT_COMPOSER_FLAGS $COMPOSER_FLAGS
                - composer info -D | sort
            script:
                - ./vendor/bin/php-cs-fixer fix -v --dry-run
                - ./vendor/bin/composer-require-checker check composer.json
